# Generated by Django 6.0.4 on 2026-05-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asignacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_liberacion", models.DateTimeField(blank=True, null=True)),
                ("motivo_reasignacion", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "asignacion",
            },
        ),
        migrations.CreateModel(
            name="Auditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "auditoria",
            },
        ),
        migrations.CreateModel(
            name="Estado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "estado",
            },
        ),
        migrations.CreateModel(
            name="Reporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_cierre_tentativa", models.DateTimeField(blank=True, null=True)),
                ("fecha_cierre_real", models.DateTimeField(blank=True, null=True)),
                (
                    "evidencia",
                    models.ImageField(blank=True, null=True, upload_to="evidencias/"),
                ),
                ("resultado_atencion", models.TextField(blank=True, null=True)),
                ("motivo_rechazo", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "reporte",
            },
        ),
        migrations.CreateModel(
            name="TipoDano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "tipo_dano",
            },
        ),
    ]
