# Generated by Django 6.0.4 on 2026-05-04 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reportes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asignacion",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="asignaciones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="auditorias",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="estado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="reportes.estado"
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reportes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditoria",
            name="reporte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auditorias",
                to="reportes.reporte",
            ),
        ),
        migrations.AddField(
            model_name="asignacion",
            name="reporte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asignaciones",
                to="reportes.reporte",
            ),
        ),
        migrations.AddField(
            model_name="reporte",
            name="tipo_dano",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="reportes.tipodano"
            ),
        ),
    ]
